### ISSUE TITLE
About the Algorithm 1 Prompt Point Generation Scheme

### ISSUE THREAD

**Issue by zzzyzh** [mazurowski-lab/segment-anything-medical-evaluation#2]
Hi,

I noticed that the code in the current repository does not seem to implement the `Algorithm 1 Prompt Point Generation Scheme`, when will you update it in this repository, please?

Your outstanding work has been very helpful and I look forward to your updates!

**Comment by haoyudong-97** [comment]
Hi,

The algorithm is implemented in the running script. 

A few key lines:
Line 347: generate the first prompt.
Line 379: compute error mask (both false positive and false negative).
Line 381: find the next prompt.
