### ISSUE TITLE
About logit < 0

### ISSUE THREAD

**Issue by zzzyzh** [mazurowski-lab/segment-anything-medical-evaluation#4]
At line 433 of the v1 code
```python
# if logit < 0, it is more like a background
preds[preds < 0] = 0 
preds = preds.transpose((1,2,0))
```
What does logit <0 mean? Why does this happen? Why do I need to use the `transpose` method?
Your excellent will be a great help to my research!

**Comment by haoyudong-97** [comment]
At line 355 of v1, we have
`preds, _, _ = predictor.predict(point_coords=np.array(pc), point_labels=np.array(pl), return_logits=True)`
So preds is a logit, and we use 0 as the threshold to determine foreground or background.

Transpose is used to make our visualization easier; you don't necessarily need it.
