### ISSUE TITLE
The accurate dice score of SAM for each segmentation task

### ISSUE THREAD

**Issue by AlfredQin** [mazurowski-lab/segment-anything-medical-evaluation#5]
Hi, thanks for your great work ! I find that there is only histograms visualization of DICE socres for each task in the paper and it seems that we can only get a rough score. So could you please share the accurate score values for each task ? By the way, could you please share the training and testing dataset ? Thank you !

**Comment by Guhanxue** [comment]
Hi, Thanks so much for your interest! May i ask which figure you are asking thus i can check the value for u!

**Comment by haoyudong-97** [comment]
Regarding the data, all of the datasets are used for testing. No training is involved in this repo.

To access the data, we suggest following their official website for downloading (which can be found in Table 1). Although all of them are publicly available, some datasets require signing user agreements and prohibit us from sharing them directly.

**Comment by MyFirst905** [comment]
Hi, thanks for your great work !  I have the same problem.Is there any specific value for this part? Could you share the details? Thank you !
<img width="883" alt="image" src="https://github.com/mazurowski-lab/segment-anything-medical-evaluation/assets/104078011/091c1cbb-fb07-4eaf-9264-4fae2ad403f1">
<img width="524" alt="image" src="https://github.com/mazurowski-lab/segment-anything-medical-evaluation/assets/104078011/f6f5d043-2b81-4c97-bdec-c50b7daa280f">

**Comment by Guhanxue** [comment]
Hi guys, sorry for the delay, we have published all the experimental results for making these tables under subfoldetr of experimental_results_tables, and hope these are helpful.
